[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unified-futures-bot"
version = "1.0.0"
dependencies = [
    "ccxt",
    "pandas",
    "numpy",
    "python-telegram-bot>=21.0",
    "nest_asyncio"
]
